version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "cd /app && yarn install && ./node_modules/.bin/nodemon --watch src src/index.js"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5000:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}

volumes:
  node_modules:
