version: '3'
services:
  app:
    build: .
    command: /bin/sh -c "cd /app && yarn install && node --watch src/index.js"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5000:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}

volumes:
  node_modules:
